export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
